# Generated by Django 4.2.3 on 2023-07-16 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 23, 21, 55, 499902)),
        ),
    ]
